Grpc:
  server.port: 50051

Dashboard:
  service.port: 9999
  service.acceptors: 5
  service.selectors: 10
  service.workers: 30

Api:
  service.port: 9998
  service.acceptors: 5
  service.selectors: 10
  service.workers: 30
  scheduledexecutor.threadpool.size: 1

Tracing:
  collector.endpoint: http://localhost:9411/api/v2/spans

database:
    validationQuery: "select 1"
    validationQueryTimeoutInSeconds: 3
    properties:
        hibernate.hbm2ddl.auto: "validate"
        hibernate.dialect: "org.hibernate.dialect.MySQLInnoDBDialect"
        hibernate.connection.driver_class: "com.mysql.jdbc.Driver"
        hibernate.connection.url: "jdbc:mysql://localhost:3306/test"
        hibernate.connection.username: "root"
        hibernate.connection.password: ""
        connection.provider_class: "org.hibernate.c3p0.internal.C3P0ConnectionProvider"
        hibernate.c3p0.min_size: 3
        hibernate.c3p0.max_size: 10